[package]
name = "tpvfitplay"
version = "0.1.0"
edition = "2021"

[dependencies]
fitparser = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
serde_json = { version = "1.0" }